<a href="https://colab.research.google.com/github/prashantmane091318/Computer_Vision/blob/main/deep_learning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
xs=np.array([-1.0,0.0,2.0,3.0,4.0,5.0,1.0])

In [ ]:
ys=np.array([-3.0,-1.0,3.0,5.0,7.0,9.0,1.0])

In [ ]:
ys

array([ 1., -1.,  3.,  5.,  7.,  9.,  1.])

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Dense

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
model.add(Dense(1,input_shape=(1,)))

In [ ]:
model.compile(optimizer="sgd",loss="mean_squared_error",metrics=["accuracy"])

In [ ]:
model.fit(xs,ys,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 6.5738 - accuracy: 0.1429
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 4.7384 - accuracy: 0.1429
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 3.4718 - accuracy: 0.1429
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 2.5966 - accuracy: 0.1429
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 1.9907 - accuracy: 0.1429
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 1.5701 - accuracy: 0.1429
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 1.2770 - accuracy: 0.1429
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 1.0718 - accuracy: 0.1429
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.9270 - accuracy: 0.1429
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.8238 - accuracy: 0.1429
Epoch 11/100
1/1 [===========

In [ ]:
model.predict([10.0])

array([[18.217659]], dtype=float32)

In [ ]:
w=np.random.rand(7,1)

In [ ]:
w

array([[0.79629289],
       [0.21357574],
       [0.77817553],
       [0.64968284],
       [0.99658824],
       [0.96915385],
       [0.90691139]])

In [ ]:
xs=xs.reshape(1,7)

In [ ]:
for i in range(100):
  result=np.dot(xs,w)
  error=ys-result
  dw=np.dot(xs.T,error*0.0001)
  w=w-dw


In [ ]:
result

array([[1.92006692e+278, 1.67148465e+278, 1.17432010e+278,
        9.25737825e+277, 6.77155552e+277, 4.28573278e+277,
        1.42290237e+278]])

In [ ]:
fashion_dataset=tf.keras.datasets.fashion_mnist

In [ ]:
(xtrain,ytrain),(xtest,ytest)=fashion_dataset.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [ ]:
xtrain.shape,ytrain.shape

((60000, 28, 28), (60000,))

In [ ]:
xtrain[0].shape

(28, 28)

In [ ]:
xtrain1=xtrain.reshape(-1,784)/255.0

In [ ]:
xtest1=xtest.reshape(-1,784)/255.0

In [ ]:
ytrain1=tf.keras.utils.to_categorical(ytrain)

In [ ]:
ytrain1.shape

(60000, 10)

In [ ]:
ytest1=tf.keras.utils.to_categorical(ytest)

In [ ]:
ytest1.shape

(10000, 10)

In [ ]:
xtest[0].shape

(28, 28)

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
from tensorflow.keras.layers import Dense,Flatten,Conv2D,MaxPool2D,LSTMCell

In [ ]:
model.add(Dense(50,activation="relu",input_shape=(784,)))

In [ ]:
model.add(Dense(10,activation="softmax"))

In [ ]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 50)                39250     
_________________________________________________________________
dense_17 (Dense)             (None, 10)                510       
Total params: 39,760
Trainable params: 39,760
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(xtrain1,ytrain1,batch_size=64,epochs=100)

Epoch 1/100
938/938 [==============================] - 2s 2ms/step - loss: 0.5551 - accuracy: 0.8081
Epoch 2/100
938/938 [==============================] - 2s 2ms/step - loss: 0.4129 - accuracy: 0.8561
Epoch 3/100
938/938 [==============================] - 2s 2ms/step - loss: 0.3774 - accuracy: 0.8670
Epoch 4/100
938/938 [==============================] - 2s 2ms/step - loss: 0.3538 - accuracy: 0.8756
Epoch 5/100
938/938 [==============================] - 2s 2ms/step - loss: 0.3371 - accuracy: 0.8803
Epoch 6/100
938/938 [==============================] - 2s 2ms/step - loss: 0.3226 - accuracy: 0.8855
Epoch 7/100
938/938 [==============================] - 2s 2ms/step - loss: 0.3127 - accuracy: 0.8883
Epoch 8/100
938/938 [==============================] - 2s 2ms/step - loss: 0.3027 - accuracy: 0.8909
Epoch 9/100
938/938 [==============================] - 2s 2ms/step - loss: 0.2936 - accuracy: 0.8936
Epoch 10/100
938/938 [==============================] - 2s 2ms/step - loss: 0.2870 - accura

In [ ]:
model1=tf.keras.models.Sequential()

In [ ]:
model1.add(Conv2D(32,(5,5),activation="relu",input_shape=(28,28,1)))

In [ ]:
xtrain2=xtrain.reshape(-1,28,28,1)/255.0

In [ ]:
xtest2=xtest.reshape(-1,28,28,1)/255.0

In [ ]:
model1.add(MaxPool2D((2,2)))

In [ ]:
model1.add(Flatten())

In [ ]:
model1.add(Dense(50,activation="relu"))

In [ ]:
model1.add(Dense(10,activation="softmax"))

In [ ]:
model1.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 24, 24, 32)        832       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 4608)              0         
_________________________________________________________________
dense_18 (Dense)             (None, 50)                230450    
_________________________________________________________________
dense_19 (Dense)             (None, 10)                510       
Total params: 231,792
Trainable params: 231,792
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model1.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model1.fit(xtrain2,ytrain1,batch_size=64,epochs=100)

Epoch 1/100
938/938 [==============================] - 30s 32ms/step - loss: 0.4687 - accuracy: 0.8337
Epoch 2/100
938/938 [==============================] - 30s 32ms/step - loss: 0.3143 - accuracy: 0.8880
Epoch 3/100
938/938 [==============================] - 30s 32ms/step - loss: 0.2748 - accuracy: 0.9006
Epoch 4/100
938/938 [==============================] - 30s 32ms/step - loss: 0.2480 - accuracy: 0.9104
Epoch 5/100
938/938 [==============================] - 30s 32ms/step - loss: 0.2268 - accuracy: 0.9171
Epoch 6/100
938/938 [==============================] - 30s 32ms/step - loss: 0.2084 - accuracy: 0.9233
Epoch 7/100
938/938 [==============================] - 30s 32ms/step - loss: 0.1929 - accuracy: 0.9288
Epoch 8/100
938/938 [==============================] - 30s 32ms/step - loss: 0.1758 - accuracy: 0.9356
Epoch 9/100
938/938 [==============================] - 30s 32ms/step - loss: 0.1626 - accuracy: 0.9401
Epoch 10/100
938/938 [==============================] - 30s 32ms/step - l

In [ ]:
def train_mnist():
    # Please write your code only where you are indicated.
    # please do not remove # model fitting inline comments.

    # YOUR CODE SHOULD START HERE

    # YOUR CODE SHOULD END HERE

    mnist = tf.keras.datasets.mnist

    (x_train, y_train),(x_test, y_test) = mnist.load_data()
    # YOUR CODE SHOULD START HERE
    x_train=x_train.reshape(-1,784)/255.0
    y_train=tf.keras.utils.to_categorical(y_train)
    x_test=x_test.reshape(-1,784)/255.0
    y_test=tf.keras.utils.to_categorical(y_test)
    # YOUR CODE SHOULD END HERE
    model = tf.keras.models.Sequential()
    from tensorflow.keras.layers import Dense
    model.add(Dense(50,activation="relu",input_shape=(784,)))
    model.add(Dense(10,activation="softmax"))

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    # model fitting
    history = model.fit(x_train,y_train,epochs=50)

    # model fitting
    return history.epoch, history.history['acc'][-1]

In [ ]:
train_mnist()

Epoch 1/50


ValueError: ignored

In [ ]:
mnist=tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()
    # YOUR CODE SHOULD START HERE
x_train=x_train.reshape(-1,784)/255.0
y_train=tf.keras.utils.to_categorical(y_train)
x_test=x_test.reshape(-1,784)/255.0

In [ ]:
x_train.shape

(60000, 784)

In [ ]:
y_train.shape

(60000, 10)