<a href="https://colab.research.google.com/github/prashantmane091318/Computer_Vision/blob/main/Flower_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/iris.data",names=["sepal length in cm",
"sepal width in cm",
"petal length in cm",
"petal width in cm","class"
],)

In [ ]:
df.head()

sepal length in cm  sepal width in cm  ...  petal width in cm        class
0                 5.1                3.5  ...                0.2  Iris-setosa
1                 4.9                3.0  ...                0.2  Iris-setosa
2                 4.7                3.2  ...                0.2  Iris-setosa
3                 4.6                3.1  ...                0.2  Iris-setosa
4                 5.0                3.6  ...                0.2  Iris-setosa

[5 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   sepal length in cm  150 non-null    float64
 1   sepal width in cm   150 non-null    float64
 2   petal length in cm  150 non-null    float64
 3   petal width in cm   150 non-null    float64
 4   class               150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
xtrain=df.drop("class",axis=1)

In [ ]:
xtrain.iloc[15]

sepal length in cm    5.7
sepal width in cm     4.4
petal length in cm    1.5
petal width in cm     0.4
Name: 15, dtype: float64

In [ ]:
ytrain=df["class"]

In [ ]:
ytrain

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(xtrain,ytrain,test_size=0.25,random_state=5)

In [ ]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((112, 4), (112,), (38, 4), (38,))

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model=DecisionTreeClassifier()

In [ ]:
model.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
model.score(x_train,y_train)

1.0

In [ ]:
model.score(x_test,y_test)

0.9473684210526315

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param={"criterion":['gini',"entropy"],"max_depth":[3,5,10,20,30,40,50],
       "min_samples_leaf":[3,5,10,20,30,40,50,100],
       "min_samples_split":[10,20,30,40,50,70],
       }

In [ ]:
grid=GridSearchCV(model,param,cv=5,verbose=2)

In [ ]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 672 candidates, totalling 3360 fits
[CV] criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10 
[CV]  criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10, total=   0.0s
[CV] criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10 
[CV]  criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10, total=   0.0s
[CV] criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10 
[CV]  criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10, total=   0.0s
[CV] criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10 
[CV]  criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10, total=   0.0s
[CV] criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10 
[CV]  criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=10, total=   0.0s
[CV] criterion=gini, max_depth=3, min_samples_leaf=3, min_samples_split=20 
[CV]  criterion=gini, max

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


Streaming output truncated to the last 5000 lines.
[CV] criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50 
[CV]  criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50, total=   0.0s
[CV] criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50 
[CV]  criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50, total=   0.0s
[CV] criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50 
[CV]  criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50, total=   0.0s
[CV] criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50 
[CV]  criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50, total=   0.0s
[CV] criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50 
[CV]  criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=50, total=   0.0s
[CV] criterion=gini, max_depth=20, min_samples_leaf=30, min_samples_split=70 
[CV]  criterion=

[Parallel(n_jobs=1)]: Done 3360 out of 3360 | elapsed:   12.9s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                   

In [ ]:
grid.best_estimator_

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=40,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
model1=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=40,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')



In [ ]:
model1.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=40,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
model1.score(x_train,y_train)

0.9732142857142857

In [ ]:
model1.score(x_test,y_test)

0.9210526315789473

In [ ]:
model1.predict([[5.7,4.4,1.5,0.3]])

array(['Iris-setosa'], dtype=object)

In [ ]:
ytrain[15]

'Iris-setosa'

In [ ]:
yp=model1.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,f1_score,recall_score,precision_score

In [ ]:
confusion_matrix(y_test,yp)

array([[12,  0,  0],
       [ 0, 13,  1],
       [ 0,  2, 10]])

In [ ]:
recall_score(y_test,yp,average=None)

array([1.        , 0.92857143, 0.83333333])

In [ ]:
f1_score(y_test,yp,average=None)

array([1.        , 0.89655172, 0.86956522])