<a href="https://colab.research.google.com/github/prashantmane091318/Computer_Vision/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[0,0,0],
             [0,0,1],
             [0,1,0],
             [0,1,1],
             [1,0,0],
             [1,0,1],
             [1,1,0],
             [1,1,1]])
y_actual = X[:,0] + X[:,1] - X[:,2]

In [ ]:
X.shape

(8, 3)

In [ ]:
np.where(y_actual>0,1,0)

array([ 0, -1,  1,  0,  1,  0,  2,  1])

In [ ]:
y_actual = np.where(y_actual>0,1,0).reshape(-1,1)

In [ ]:
y_actual

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [ ]:
W = np.random.randn(3,1)
W

array([[ 2.11552311],
       [ 0.204649  ],
       [-0.09539394]])

In [ ]:
def sigmoid(P):
    return 1/(1+np.exp(-P))

In [ ]:
for i in range(100): #epochs
    y_predict = sigmoid(np.dot(X,W))
    error = y_predict - y_actual
    dw = np.dot(X.T,error)
    W = W - dw

In [ ]:
W

array([[ 4.84238843],
       [ 4.84263877],
       [-7.42113116]])

In [ ]:
y_actual

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [ ]:
np.round(sigmoid(np.dot(X,W)))

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.]])

In [ ]:
X = np.random.random((50,1))
y_actual = X*2

In [ ]:
W = np.random.randn(1,1)

In [ ]:
W

array([[-0.98538029]])

In [ ]:
for i in range(50):
    y_predict = np.dot(X,W) #linear
    error = y_predict - y_actual
    dw = np.dot(X.T,error*0.01)
    W = W - dw

In [ ]:
W

array([[1.99923852]])

array([[0.53826231, 0.28953327, 0.28972631],
       [0.22363859, 0.05267322, 0.05001422],
       [0.30835192, 0.10188203, 0.09508091],
       [0.40801784, 0.15942181, 0.16647856],
       [0.23265486, 0.04963085, 0.05412828],
       [0.27789491, 0.07629592, 0.07722558],
       [0.98163296, 0.96816014, 0.96360327],
       [0.66834898, 0.44481406, 0.44669036],
       [0.67254199, 0.44437855, 0.45231272],
       [0.32108039, 0.1284243 , 0.10309262],
       [0.4778013 , 0.23561639, 0.22829409],
       [0.5230546 , 0.26599987, 0.27358611],
       [0.67788381, 0.44334709, 0.45952646],
       [0.84624841, 0.71214729, 0.71613636],
       [0.23480922, 0.04868746, 0.05513537],
       [0.82330837, 0.66808551, 0.67783667],
       [0.19069491, 0.04030168, 0.03636455],
       [0.50759009, 0.27433786, 0.2576477 ],
       [0.22570293, 0.05312489, 0.05094181],
       [0.40378819, 0.14451403, 0.1630449 ],
       [0.54647821, 0.30416769, 0.29863844],
       [0.94686391, 0.88124752, 0.89655127],
       [0.